SELECT TOP 10 CASE WHEN ISNUMERIC(SUBSTRING(RFC,4,1)) = 0 AND ISNUMERIC(SUBSTRING(RFC,5,1)) = 1
THEN
YEAR(GETDATE()) - CASE WHEN CAST(SUBSTRING(RFC,5,2) AS INT) BETWEEN 0 AND RIGHT(YEAR(GETDATE()),2) THEN '20' + SUBSTRING(RFC,5,2) ELSE '19' +SUBSTRING(RFC,5,2) END
ELSE NULL END edad
FROM  db..Cuentas